title: Data Analyst / Business Intelligence
logo: image 2 portfolio jpeg.jpeg
#description: text below the image
avatar_caption: a data enthusiast with a love for AI,ML and analytics.
show_downloads: true
theme: jekyll-theme-minimal
